spring:
  application:
    name: acuerdos-monitor-sqlite
  datasource:
    url: jdbc:sqlite:${SQLITE_DB_PATH:./data/acuerdos.db}
    driver-class-name: org.sqlite.JDBC
  flyway:
    enabled: true
    locations: classpath:db/migration

server:
  port: ${PORT:8080}

monitor:
  enabled: true
  cron: "0 30 15 * * MON-FRI"
  zone: America/Mexico_City
  juzgados:
    - clave: 1RG
      nombre: Rio Grande Primero Mixto
    - clave: 2RG
      nombre: Rio Grande Segundo Mixto
    - clave: 3RG
      nombre: Rio Grande Tercero Mixto

tsj:
  base-url: https://apps.pjzac.gob.mx

telegram:
  enabled: "true"
  bot-token: "8250681484:AAFs3LvSookCYDkl0qrNh1Ini_DzzJeqXvk"
  chat-id: "6267702178"
management:
  endpoints:
    web:
      exposure:
        include: health,info
