name: Revisar acuerdos TSJ

on:
  schedule:
    - cron: "07 14 * * 1-5"
      timezone: 'America/Mexico_City'   

  workflow_dispatch:

jobs:
  revisar-acuerdos:
    runs-on: ubuntu-latest

    steps:
      - name: Llamar endpoint de revisión
        run: |
          echo "Ejecutando revisión de acuerdos..."
          curl --fail --show-error --location --max-time 120 -X GET "${{ secrets.RENDER_MONITOR_URL }}"
