name: Revisar acuerdos TSJ

on:
  schedule:
    - cron: "55 16 * * 1-5"
    - cron: "0 17 * * 1-5"
    - cron: "5 17 * * 1-5"
    - cron: "10 17 * * 1-5"

  workflow_dispatch:

jobs:
  revisar-acuerdos:
    runs-on: ubuntu-latest

    steps:
      - name: Llamar endpoint de revisión
        run: |
          echo "Ejecutando revisión de acuerdos..."
          curl --fail --show-error --location --max-time 120 -X GET "${{ secrets.RENDER_MONITOR_URL }}"
